version: "3.9"

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - "6379:6379"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb

networks:
  backend:
    external: true
